# Generated by Django 5.1.6 on 2025-02-09 16:56

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=blogs.models.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
